# Generated by Django 4.2.5 on 2023-11-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blogpost_chead0_alter_blogpost_chead1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="chead0",
            field=models.TextField(default="", max_length=5000),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="chead1",
            field=models.TextField(default="", max_length=5000),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="chead2",
            field=models.TextField(default="", max_length=5000),
        ),
    ]
