# Generated by Django 4.2.5 on 2023-11-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_contact_alter_product_desc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("items_json", models.CharField(max_length=50000)),
                ("name", models.CharField(max_length=90)),
                ("email", models.CharField(max_length=90)),
                ("address", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=90)),
                ("state", models.CharField(max_length=90)),
                ("zip_code", models.IntegerField(max_length=90)),
            ],
        ),
    ]
