# Generated by Django 4.2.5 on 2023-11-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="zip_code",
            field=models.IntegerField(),
        ),
    ]
