# Generated by Django 4.2.5 on 2023-11-07 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_orders_zip_code"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Orders",
            new_name="Order",
        ),
    ]
