# Generated by Django 4.2.5 on 2023-11-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_rename_orders_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.IntegerField(default=0),
        ),
    ]
