# Generated by Django 4.2.5 on 2023-11-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_order_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=90),
        ),
    ]
