# Generated by Django 4.2.5 on 2023-11-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_orderupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderupdate",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
