# Generated by Django 4.2.5 on 2023-11-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_alter_orderupdate_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
