# Generated by Django 4.2.5 on 2023-11-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_order_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name="order",
            name="items_json",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(default="", max_length=111),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name="order",
            name="zip_code",
            field=models.CharField(max_length=111),
        ),
    ]
