# Generated by Django 4.2.7 on 2023-11-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_alter_order_address_alter_order_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderupdate",
            name="timestamp",
            field=models.DateTimeField(default="2023/11/18 04:11:55"),
        ),
    ]
