# Generated by Django 4.0.6 on 2023-11-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_orderupdate_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default='2023-11-19 14:16:10'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default='No description Provided.', max_length=4000),
        ),
    ]
