# Generated by Django 4.0.6 on 2023-11-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_orderupdate_timestamp_alter_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default='2023-11-20 21:21:00'),
        ),
    ]
