# Generated by Django 4.2.5 on 2023-11-19 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0015_alter_orderupdate_timestamp_alter_product_desc"),
        ("shop", "0016_alter_orderupdate_timestamp_alter_product_desc"),
    ]

    operations = []
