# Generated by Django 4.2.5 on 2023-12-08 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0017_merge_20231119_1513"),
        ("shop", "0018_alter_orderupdate_timestamp"),
    ]

    operations = []
