name: Django CI/CD

on:
  push:
    branches: [ master ] # Adjust branch as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # Use your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        cd TextUtils && python manage.py test

    # Add deployment steps below if needed
    # - name: Deploy to server
    #   run: |
    #     Your deployment commands here

    # Remember to use secrets or environment variables for sensitive information

